package v0

// BabylonStakingEarlyUnbond struct for BabylonStakingEarlyUnbond
type BabylonStakingEarlyUnbond struct {
	BabylonScriptData
	// The transaction-id of the staking transaction to unbond.
	TxId string `json:"txid"`
	// An optional lock height (in blocks) for this transaction. The resulting transaction cannot be mined before the specified block height.
	TxnLockHeight *int32 `json:"txn_lock_height,omitempty"`
	// The value in sats that was staked in the deposit transaction.
	Value int64 `json:"value"`
	// The transaction output index of the staking transaction to unbond. For staking transactions generated by CubeSigner, this will always be zero.
	Vout int32 `json:"vout"`
	// The action type.
	Action BabylonStakingAction `json:"action"`
}

func NewBabylonStakingEarlyUnbond(scriptData BabylonScriptData, txId string, value int64, vout int32, action BabylonStakingAction) *BabylonStakingEarlyUnbond {
	this := BabylonStakingEarlyUnbond{}
	this.Action = action
	this.BabylonScriptData = scriptData
	this.TxId = txId
	this.Value = value
	this.Vout = vout
	return &this
}

func NewBabylonStakingEarlyUnbondWithDefaults() *BabylonStakingEarlyUnbond {
	this := BabylonStakingEarlyUnbond{}
	return &this
}

func (o *BabylonStakingEarlyUnbond) GetAction() BabylonStakingAction {
	if o == nil {
		return ""
	}
	return o.Action
}

func (o *BabylonStakingEarlyUnbond) GetActionOk() (BabylonStakingAction, bool) {
	if o == nil {
		return "", false
	}
	return o.Action, true
}

func (o *BabylonStakingEarlyUnbond) SetAction(v BabylonStakingAction) {
	o.Action = v
}

func (o *BabylonStakingEarlyUnbond) GetTxId() string {
	if o == nil {
		return ""
	}
	return o.TxId
}

func (o *BabylonStakingEarlyUnbond) GetTxIdOk() (string, bool) {
	if o == nil {
		return "", false
	}
	return o.TxId, true
}

func (o *BabylonStakingEarlyUnbond) SetTxId(v string) {
	o.TxId = v
}

func (o *BabylonStakingEarlyUnbond) GetTxnLockHeight() *int32 {
	if o == nil {
		return nil
	}
	return o.TxnLockHeight
}

func (o *BabylonStakingEarlyUnbond) GetTxnLockHeightOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.TxnLockHeight, true
}

func (o *BabylonStakingEarlyUnbond) SetTxnLockHeight(v *int32) {
	o.TxnLockHeight = v
}

func (o *BabylonStakingEarlyUnbond) GetValue() int64 {
	if o == nil {
		return 0
	}
	return o.Value
}

func (o *BabylonStakingEarlyUnbond) GetValueOk() (int64, bool) {
	if o == nil {
		return 0, false
	}
	return o.Value, true
}

func (o *BabylonStakingEarlyUnbond) SetValue(v int64) {
	o.Value = v
}

func (o *BabylonStakingEarlyUnbond) GetVout() int32 {
	if o == nil {
		return 0
	}
	return o.Vout
}

func (o *BabylonStakingEarlyUnbond) GetVoutOk() (int32, bool) {
	if o == nil {
		return 0, false
	}
	return o.Vout, true
}

func (o *BabylonStakingEarlyUnbond) SetVout(v int32) {
	o.Vout = v
}
